export const LOAD_CLASSROOM = "LOAD_CLASSROOM";
export const SET_CURRENT_SUBJECT = "SET_CURRENT_SUBJECT";

export const LOAD_SUBJECT_NOTES = "LOAD_SUBJECT_NOTES";
export const LOAD_SUBJECT_ASSIGNMENTS = "LOAD_SUBJECT_ASSIGNMENTS";

// Notifications
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";

//SUCCESS_SUBMIT_ASSIGNMENT
export const REMOVE_ASSIGNMENT = "REMOVE_ASSIGNMENT";

// SUBJECT RESULTS
export const LOAD_SUBJECT_EXAMS_RESULT = "LOAD_SUBJECT_EXAMS_RESULT";
