export const LOAD_CLASSROOM = "LOAD_CLASSROOM";
export const SET_CURRENT_SUBJECT = "SET_CURRENT_SUBJECT";

export const LOAD_SUBJECT_NOTES = "LOAD_SUBJECT_NOTES";
export const LOAD_SUBJECT_ASSIGNMENTS = "LOAD_SUBJECT_ASSIGNMENTS";
