# Generated by Django 3.1.5 on 2021-06-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210627_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradedassignment',
            old_name='gradepoints',
            new_name='points',
        ),
    ]
