# Generated by Django 3.1.5 on 2021-07-01 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='document_file',
            field=models.FileField(default='demo.jpg', upload_to='leave_request/documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 12, 45, 53, 224016, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 12, 45, 58, 840225, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
