# Generated by Django 3.1.5 on 2021-07-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210701_1358'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leaverequest',
            table='leave_requests',
        ),
    ]
